[package]
name = "aoye"
version = "0.1.0"
authors = ["duchaoqun <du.chao.qun@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
