[package]
name = "aoye"
version = "0.0.1"
authors = ["duchaoqun <du.chaoqun@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.3"
lettre = "0.9.5"
lettre_email = "0.9"